services:
  db:
    image: postgres:latest
    container_name: jobtracker-db
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  web:
    build: .
    container_name: jobtracker
    ports:
      - "3000:3000"
    env_file: ./.env
    volumes:
      - .:/jobtracker
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
